{% set name = "pyslim" %}
{% set version = "1.1.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5cfc04427cdd3df94fb149ba511e674c2212c581f6f31e9422171fa98ba9a399

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - attrs
    - kastore
    - msprime 
    - numpy
    - tskit

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyslim

about:
  home: https://github.com/tskit-dev/pyslim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for dealing with tree sequences coming to and from SLiM.
  description: |
    pyslim is a python module to allow reading and writing of SLiM-produced tree
    sequences as a thin interface to tskit. 
  doc_url: https://tskit.dev/pyslim/docs/
  dev_url: https://tskit.dev/pyslim/docs/stable/development.html

extra:
  recipe-maintainers:
    - winni2k
    - jeromekelleher
    - petrelharp
