{% set name = "pyslim" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bda94084f11564dbff2187bce5af3c48613edbff4ed689af072c33fc779e45ca

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - attrs
    - kastore
    - msprime >=0.7.0
    - numpy
    - tskit

test:
  imports:
    - pyslim

about:
  home: https://github.com/tskit-dev/pyslim
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Tools for dealing with tree sequences coming to and from SLiM.
  description: |
    pyslim is a python module to allow reading and writing of SLiM-produced tree
    sequences as a thin interface to tskit. 
  doc_url: https://pyslim.readthedocs.io/en/latest/
  dev_url: https://pyslim.readthedocs.io/en/latest/development.html

extra:
  recipe-maintainers:
    - winni2k
    - jeromekelleher
    - petrelharp
